// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyABE4y6P1R9iEBZBQp0-b1kzU4-1__qM8U',
    appId: '1:82958019535:web:b1d8f8580aaae932ce40ba',
    messagingSenderId: '82958019535',
    projectId: 'dangdang-v2-9fc24',
    authDomain: 'dangdang-v2-9fc24.firebaseapp.com',
    storageBucket: 'dangdang-v2-9fc24.firebasestorage.app',
    measurementId: 'G-QVYRLWQ4MQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-VQ6QLaUbQck-MXDLUiPFR0k0G2yshDc',
    appId: '1:82958019535:android:50fc4ca54a0fee6bce40ba',
    messagingSenderId: '82958019535',
    projectId: 'dangdang-v2-9fc24',
    storageBucket: 'dangdang-v2-9fc24.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyABE4y6P1R9iEBZBQp0-b1kzU4-1__qM8U',
    appId: '1:82958019535:web:c3c8f47969aa4758ce40ba',
    messagingSenderId: '82958019535',
    projectId: 'dangdang-v2-9fc24',
    authDomain: 'dangdang-v2-9fc24.firebaseapp.com',
    storageBucket: 'dangdang-v2-9fc24.firebasestorage.app',
    measurementId: 'G-17Q9PF6D54',
  );
}
